package Telas;


import Telas.views.CRUD.*;
import com.formdev.flatlaf.intellijthemes.FlatArcOrangeIJTheme;
import java.awt.BorderLayout;
import java.time.LocalDate;
import javax.swing.JPanel;
import javax.swing.UIManager;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author HP
 */
public class Dashboard1 extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard1
     */
    public Dashboard1() {
        initComponents();
        setData();
        initPrincipal();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        Menu = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        nome = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        BtDashboard = new javax.swing.JButton();
        BtFuncionarios = new javax.swing.JButton();
        BtPaciente = new javax.swing.JButton();
        BtEspecialidade = new javax.swing.JButton();
        BtConsultas = new javax.swing.JButton();
        BtFacturas = new javax.swing.JButton();
        Subtitulo = new javax.swing.JLabel();
        BtMedicamentos = new javax.swing.JButton();
        Barra_Superior = new javax.swing.JPanel();
        Data_actual = new javax.swing.JLabel();
        Fundo_principal = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1035, 576));

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setMinimumSize(new java.awt.Dimension(1035, 594));
        background.setPreferredSize(new java.awt.Dimension(1035, 576));

        Menu.setBackground(new java.awt.Color(51, 204, 255));

        nome.setBackground(new java.awt.Color(255, 255, 255));
        nome.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nome.setForeground(new java.awt.Color(255, 255, 255));
        nome.setText("Clinica Girassol");

        Email.setBackground(new java.awt.Color(255, 255, 255));
        Email.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Email.setForeground(new java.awt.Color(255, 255, 255));
        Email.setText("info.clinica@girassol.co.ao");

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        BtDashboard.setBackground(new java.awt.Color(29, 163, 207));
        BtDashboard.setForeground(new java.awt.Color(255, 255, 255));
        BtDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/home-outline.png"))); // NOI18N
        BtDashboard.setText("Dashboard");
        BtDashboard.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 15, 1, 1, new java.awt.Color(0, 0, 0)));
        BtDashboard.setBorderPainted(false);
        BtDashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtDashboard.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        BtDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtDashboardActionPerformed(evt);
            }
        });

        BtFuncionarios.setBackground(new java.awt.Color(29, 163, 207));
        BtFuncionarios.setForeground(new java.awt.Color(255, 255, 255));
        BtFuncionarios.setText("Funcionarios");
        BtFuncionarios.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 15, 1, 1, new java.awt.Color(0, 0, 0)));
        BtFuncionarios.setBorderPainted(false);
        BtFuncionarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtFuncionarios.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        BtFuncionarios.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        BtFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtFuncionariosActionPerformed(evt);
            }
        });

        BtPaciente.setBackground(new java.awt.Color(29, 163, 207));
        BtPaciente.setForeground(new java.awt.Color(255, 255, 255));
        BtPaciente.setText("Pacientes");
        BtPaciente.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 15, 1, 1, new java.awt.Color(0, 0, 0)));
        BtPaciente.setBorderPainted(false);
        BtPaciente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtPaciente.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        BtPaciente.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        BtPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtPacienteActionPerformed(evt);
            }
        });

        BtEspecialidade.setBackground(new java.awt.Color(29, 163, 207));
        BtEspecialidade.setForeground(new java.awt.Color(255, 255, 255));
        BtEspecialidade.setText("Especialidades");
        BtEspecialidade.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 15, 1, 1, new java.awt.Color(0, 0, 0)));
        BtEspecialidade.setBorderPainted(false);
        BtEspecialidade.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtEspecialidade.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        BtEspecialidade.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        BtEspecialidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtEspecialidadeActionPerformed(evt);
            }
        });

        BtConsultas.setBackground(new java.awt.Color(29, 163, 207));
        BtConsultas.setForeground(new java.awt.Color(255, 255, 255));
        BtConsultas.setText("Consultas");
        BtConsultas.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 15, 1, 1, new java.awt.Color(0, 0, 0)));
        BtConsultas.setBorderPainted(false);
        BtConsultas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtConsultas.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        BtConsultas.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        BtConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtConsultasActionPerformed(evt);
            }
        });

        BtFacturas.setBackground(new java.awt.Color(29, 163, 207));
        BtFacturas.setForeground(new java.awt.Color(255, 255, 255));
        BtFacturas.setText("Facturas");
        BtFacturas.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 15, 1, 1, new java.awt.Color(0, 0, 0)));
        BtFacturas.setBorderPainted(false);
        BtFacturas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtFacturas.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        BtFacturas.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        BtFacturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtFacturasActionPerformed(evt);
            }
        });

        Subtitulo.setText("Entidades");

        BtMedicamentos.setBackground(new java.awt.Color(29, 163, 207));
        BtMedicamentos.setForeground(new java.awt.Color(255, 255, 255));
        BtMedicamentos.setText("Medicamentos");
        BtMedicamentos.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 15, 1, 1, new java.awt.Color(0, 0, 0)));
        BtMedicamentos.setBorderPainted(false);
        BtMedicamentos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtMedicamentos.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        BtMedicamentos.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        BtMedicamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtMedicamentosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(nome))
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(Email))
            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(BtDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(MenuLayout.createSequentialGroup()
                .addComponent(Subtitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10))
            .addComponent(BtFuncionarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BtPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BtEspecialidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BtConsultas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BtFacturas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BtMedicamentos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(nome)
                .addGap(6, 6, 6)
                .addComponent(Email)
                .addGap(6, 6, 6)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(BtDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(Subtitulo)
                .addGap(4, 4, 4)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(MenuLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(BtPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(BtEspecialidade, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(BtConsultas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(BtFacturas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(BtMedicamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Barra_Superior.setBackground(new java.awt.Color(238, 234, 234));

        Data_actual.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Data_actual.setText("Data actual");

        Fundo_principal.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout Fundo_principalLayout = new javax.swing.GroupLayout(Fundo_principal);
        Fundo_principal.setLayout(Fundo_principalLayout);
        Fundo_principalLayout.setHorizontalGroup(
            Fundo_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        Fundo_principalLayout.setVerticalGroup(
            Fundo_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 551, Short.MAX_VALUE)
        );

        jButton1.setBackground(new java.awt.Color(29, 163, 207));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Sair");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Barra_SuperiorLayout = new javax.swing.GroupLayout(Barra_Superior);
        Barra_Superior.setLayout(Barra_SuperiorLayout);
        Barra_SuperiorLayout.setHorizontalGroup(
            Barra_SuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Barra_SuperiorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Data_actual, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 485, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
            .addComponent(Fundo_principal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Barra_SuperiorLayout.setVerticalGroup(
            Barra_SuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Barra_SuperiorLayout.createSequentialGroup()
                .addGroup(Barra_SuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Data_actual)
                    .addGroup(Barra_SuperiorLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Fundo_principal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(Menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Barra_Superior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(Barra_Superior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtEspecialidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtEspecialidadeActionPerformed
        initViews(new EspecialidadeCRUD());
    }//GEN-LAST:event_BtEspecialidadeActionPerformed

    private void BtConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtConsultasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtConsultasActionPerformed

    private void BtFacturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtFacturasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtFacturasActionPerformed

    private void BtMedicamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtMedicamentosActionPerformed
        initViews(new MedicamentoCRUD());
    }//GEN-LAST:event_BtMedicamentosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BtDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtDashboardActionPerformed
        initViews(new Principal());
    }//GEN-LAST:event_BtDashboardActionPerformed

    private void BtFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtFuncionariosActionPerformed
        initViews(new FuncionarioCRUD());
    }//GEN-LAST:event_BtFuncionariosActionPerformed

    private void BtPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtPacienteActionPerformed
        initViews(new PacienteCRUD());
    }//GEN-LAST:event_BtPacienteActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jButton1MouseClicked

    private void setData(){
        LocalDate data =  LocalDate.now();
        int ano = data.getYear();
        int mes = data.getMonthValue();
        int dia = data.getDayOfMonth();
        String [] meses = {"Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", 
            "Novembro", "Dezembro"};
        Data_actual.setText("Hoje, "+dia+" de "+meses[mes -1] +" de "+ano);
    }
    private void initPrincipal() {
        initViews(new Principal());
    }
    
    private void initViews(JPanel pl){
       // Principal p1 = new Principal();
        pl.setSize(759, 533);
        pl.setLocation(0,0);
       Fundo_principal.removeAll();
        Fundo_principal.add(pl, BorderLayout.CENTER);
        Fundo_principal.revalidate();
        Fundo_principal.repaint();
        
    }
    
    public static void main(String args[]) {
  FlatArcOrangeIJTheme.setup();
  UIManager.put( "Button.arc", 999 );

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Barra_Superior;
    private javax.swing.JButton BtConsultas;
    private javax.swing.JButton BtDashboard;
    private javax.swing.JButton BtEspecialidade;
    private javax.swing.JButton BtFacturas;
    private javax.swing.JButton BtFuncionarios;
    private javax.swing.JButton BtMedicamentos;
    private javax.swing.JButton BtPaciente;
    private javax.swing.JLabel Data_actual;
    private javax.swing.JLabel Email;
    private javax.swing.JPanel Fundo_principal;
    private javax.swing.JLabel Logo;
    private javax.swing.JPanel Menu;
    private javax.swing.JLabel Subtitulo;
    private javax.swing.JPanel background;
    private javax.swing.JButton jButton1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel nome;
    // End of variables declaration//GEN-END:variables
}
